version: '2.1'
services:

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mysql/config/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1

  elasticsearch:
    build: elasticsearch
    mem_limit: 4g
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
      - ./elasticsearch/config/userdict_ja.txt:/usr/share/elasticsearch/config/userdict_ja.txt
      - ./elasticsearch/logs/:/var/log/elasticsearch/
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.4
    ports:
      - 5601:5601
    environment:
      - xpack.security.enabled=false